class AppStrings {
  static const Map<String, String> languageNames = {
    'mr': 'मराठी (Marathi)',
    'hi': 'हिंदी (Hindi)',
    'en': 'English',
    'es': 'Español',
  };

  static const Map<String, String> languageCodes = {
    'mr': 'मराठी',
    'hi': 'हिंदी',
    'en': 'English',
    'es': 'Español',
  };

  static const Map<String, Map<String, String>> _localizedValues = {
    'mr': {
      'welcomeBack': 'पुन्हा स्वागत आहे',
      'goodEvening': 'नमस्कार, शेफ! 👋',
      'searchHint': 'रेसिपी, भाजी, साहित्य शोधा...',
      'recipeOfTheDay': 'आजची खास रेसिपी',
      'editorsPick': "शेफची पहिली पसंती",
      'foodCategories': 'रेसिपी प्रकार',
      'all': 'सर्व रेसिपी',
      'maharashtrian': 'महाराष्ट्रीयन खास',
      'breakfast': 'खमंग नाश्ता',
      'traditional': 'पारंपरिक जेवण',
      'streetFood': 'स्ट्रीट फूड',
      'fasting': 'उपवास स्पेशल',
      'sweets': 'गोडधोड',
      'trendingNow': 'लोकप्रिय महाराष्ट्रीयन डिशेस',
      'recipesCount': 'रेसिपी',
      'noRecipesFound': 'कोणतीही रेसिपी सापडली नाही.',

      // Bottom Nav
      'home': 'होम',
      'mealPlanner': 'काय बनवायचं?',
      'generator': 'रेसिपी AI',
      'saved': 'माझ्या रेसिपी',

      // Meal Suggestion & Planner
      'mealSuggestionTitle': 'आज जेवणात काय बनवायचं?',
      'mealSuggestionSubtitle':
          'घरातील भाज्या निवडा आणि काल काय बनवले होते ते सांगा; AI रिपीट न करता परिपूर्ण थाळी सुचवेल!',
      'mealTime': 'जेवणाची वेळ',
      'breakfastOpt': '🥐 सकाळचा नाश्ता',
      'lunchOpt': '🍛 दुपारचे जेवण',
      'dinnerOpt': '🍲 रात्रीचे जेवण',
      'availableVeggies': 'घरात कोणत्या भाज्या उपलब्ध आहेत?',
      'familyMembers': 'व्यक्तींची संख्या',
      'cookingTime': 'स्वयंपाकासाठी उपलब्ध वेळ',
      'cookedYesterday': 'काल जेवणात काय बनवलं होतं? (डिश रिपीट टाळण्यासाठी)',
      'yesterdayHint': 'उदा. बटाटा भाजी, पनीर, मटकी उसळ, अंडी...',
      'suggestMealBtn': 'आजचा परिपूर्ण मेनू सुचवा ✨',
      'suggestingMeal': 'स्मार्ट AI मेनू शोधत आहे...',
      'todaysRecommendation': 'आजचा सुचवलेला मेनू 🍽️',
      'whyThisDish': 'ही भाजी का सुचवली? (AI विश्लेषण)',
      'completeThali': 'परिपूर्ण थाळी कॉम्बिनेशन',
      'suggestAnother': 'दुसरी भाजी सुचवा 🔄',
      'startCookingThis': 'ही भाजी बनवायला घ्या 👨‍🍳',
      'weeklyPlannerTab': 'आठवड्याचे नियोजन',
      'dailySuggestionTab': 'दैनिक भाजी मेनू',
      'weeklyPlannerTitle': '७ दिवसांचे स्मार्ट जेवण नियोजन 📅',
      'weeklyPlannerSubtitle':
          'घरच्या गृहिणींसाठी दररोजचे संतुलित व पोषणयुक्त जेवण वेळापत्रक',

      // Pantry & Generator Screen
      'smartPantryTitle': 'किचन रेसिपी AI जनरेटर',
      'aiKitchenAssistant': 'GEMINI AI कुकिंग शेफ',
      'fridgeQuestion': "आज स्वयंपाकघरात काय साहित्य आहे?",
      'fridgeSubtitle':
          'साहित्य निवडा किंवा नाव टाका; जेमिनी AI अस्सल चवीची, अचूक प्रमाणासह नवीन रेसिपी तयार करेल!',
      'addCustom': 'इतर साहित्य जोडा',
      'customInputHint': 'उदा. कांदा, लसूण, पोहे, बेसन, मटकी...',
      'selectedIngredients': 'निवडलेले साहित्य',
      'readyToCook': 'रेसिपीसाठी सज्ज! ✨',
      'selectAtLeastOne': 'किमान १ साहित्य निवडा',
      'noIngredientsAdded':
          'अद्याप कोणतेही साहित्य निवडलेले नाही. खालील साहित्यावर टॅप करा!',
      'pantryStaples': 'किचनमधील रोजचे साहित्य (QUICK ADD)',
      'dietaryPreferences': 'खाण्याच्या आवडी / डाएट',
      'generateBtn': 'AI सह अस्सल रेसिपी बनवा ✨',
      'generatingBtn': 'शेफ जेमिनी रेसिपी तयार करत आहे...',
      'clearAll': 'सर्व हटवा',
      'addedIngredient': 'साहित्य जोडले गेले!',
      'pleaseSelectIngredient': 'कृपया किमान १ तरी साहित्य निवडा!',

      // Recipe Result Screen
      'prepTime': 'वेळ',
      'calories': 'कॅलरी',
      'servings': 'प्रमाण',
      'ingredientsList': 'आवश्यक साहित्य व प्रमाण',
      'checkedOf': 'पैकी',
      'checked': 'तयार',
      'toggleAll': 'सर्व निवडा',
      'stepByStep': 'कृती (Step-by-Step कृतीचे टप्पे)',
      'steps': 'टप्पे',
      'save': 'सेव्ह करा',
      'savedBtn': 'सेव्ह केले',
      'startCooking': 'कुकिंग मोड सुरू करा 👨‍🍳',
      'cookingMode': 'लाईव्ह कुकिंग मोड',
      'step': 'टप्पा',
      'stepTimer': 'टायमर',
      'startTimer': 'टायमर सुरू करा',
      'pause': 'थांबवा',
      'reset': 'रिसेट',
      'previous': 'मागील टप्पा',
      'nextStep': 'पुढील टप्पा →',
      'finishCooking': 'स्वयंपाक पूर्ण झाला! 🎉',
      'timerFinished': 'वेळ पूर्ण झाली! ⏰',
      'dishCompleted': 'वाह! तुमची डिश तयार झाली आहे! गरमागरम आस्वाद घ्या! 🍽️',
      'savedToCookbook': 'रेसिपी सेव्ह झाली! 🧡',
      'removedFromSaved': 'सेव्ह लिस्टमधून काढले',

      // Saved Recipes Screen
      'mySavedRecipes': 'माझ्या सेव्ह केलेल्या रेसिपी',
      'recipesSaved': 'रेसिपी सेव्ह केल्या',
      'filterSavedHint': 'सेव्ह केलेल्या रेसिपी शोधा...',
      'noSavedYet': 'अद्याप एकही रेसिपी सेव्ह केलेली नाही',
      'noSavedDesc':
          'होम स्क्रीनवरून तुमच्या आवडत्या महाराष्ट्रीयन रेसिपी सेव्ह करा किंवा AI ने नवीन तयार करा.',
      'exploreFeed': 'रेसिपी पहा',
      'pantryGen': 'नवीन रेसिपी बनवा',

      // Language Modal
      'selectLanguage': 'भाषा निवडा / Choose Language',
      'languageDesc': 'आपल्या आवडीनुसार संपूर्ण ॲप आणि रेसिपीसाठी भाषा निवडा.',
    },
    'hi': {
      'welcomeBack': 'वापसी पर स्वागत है',
      'goodEvening': 'नमस्ते, शेफ़! 👋',
      'searchHint': 'रेसिपी, सामग्री खोजें...',
      'recipeOfTheDay': 'आज की खास रेसिपी',
      'editorsPick': "शेफ़ की पसंद",
      'foodCategories': 'व्यंजन श्रेणियां',
      'all': 'सभी रेसिपी',
      'maharashtrian': 'महाराष्ट्रीयन खास',
      'breakfast': 'स्वादिष्ट नाश्ता',
      'traditional': 'पारंपरिक भोजन',
      'streetFood': 'स्ट्रीट फूड',
      'fasting': 'व्रत/उपवास स्पेशल',
      'sweets': 'मिठाई',
      'trendingNow': 'लोकप्रिय भारतीय व्यंजन',
      'recipesCount': 'रेसिपी',
      'noRecipesFound': 'कोई रेसिपी नहीं मिली.',

      // Bottom Nav
      'home': 'होम',
      'mealPlanner': 'क्या बनाएं?',
      'generator': 'रेसिपी AI',
      'saved': 'सेव की गई',

      // Meal Suggestion & Planner
      'mealSuggestionTitle': 'आज खाने में क्या बनाएं?',
      'mealSuggestionSubtitle':
          'घर में उपलब्ध सब्जियां चुनें और बताएं कल क्या बना था; AI बिना रिपीट किए परफेक्ट थाली सुझाएगा!',
      'mealTime': 'भोजन का समय',
      'breakfastOpt': '🥐 सुबह का नाश्ता',
      'lunchOpt': '🍛 दोपहर का खाना',
      'dinnerOpt': '🍲 रात का खाना',
      'availableVeggies': 'घर में कौन सी सब्जियां हैं?',
      'familyMembers': 'सदस्यों की संख्या',
      'cookingTime': 'पकाने का समय',
      'cookedYesterday': 'कल क्या बना था? (रिपीट से बचने के लिए)',
      'yesterdayHint': 'उदा. आलू गोभी, पनीर, दाल मखनी...',
      'suggestMealBtn': 'आज का परफेक्ट मेन्यू सुझाएं ✨',
      'suggestingMeal': 'स्मार्ट AI सोच रहा है...',
      'todaysRecommendation': 'आज का सुझाया गया मेन्यू 🍽️',
      'whyThisDish': 'यह डिश क्यों सुझाई गई? (AI कारण)',
      'completeThali': 'पूरी थाली कॉम्बिनेशन',
      'suggestAnother': 'कोई और सब्जी सुझाएं 🔄',
      'startCookingThis': 'यह सब्जी बनाना शुरू करें 👨‍🍳',
      'weeklyPlannerTab': 'हफ़्ते का प्लान',
      'dailySuggestionTab': 'दैनिक सब्जी सुझाव',
      'weeklyPlannerTitle': '७ दिनों का स्मार्ट मील प्लान 📅',
      'weeklyPlannerSubtitle':
          'गृहणियों के लिए रोज़ का संतुलित और स्वादिष्ट आहार चार्ट',

      // Pantry & Generator Screen
      'smartPantryTitle': 'रसोई रेसिपी AI जनरेटर',
      'aiKitchenAssistant': 'GEMINI AI कुकिंग शेफ़',
      'fridgeQuestion': "आज आपकी रसोई में क्या सामग्री है?",
      'fridgeSubtitle':
          'सामग्री चुनें और जेमिनी AI सटीक मात्रा और समय के साथ असली स्वादिष्ट रेसिपी तैयार करेगा.',
      'addCustom': 'अन्य सामग्री जोड़ें',
      'customInputHint': 'उदा. प्याज, आलू, पोहा, बेसन, मटर...',
      'selectedIngredients': 'चुनी गई सामग्री',
      'readyToCook': 'रेसिपी के लिए तैयार! ✨',
      'selectAtLeastOne': 'कम से कम 1 सामग्री चुनें',
      'noIngredientsAdded':
          'अभी कोई सामग्री नहीं चुनी गई. नीचे दिए गए विकल्पों पर टैप करें!',
      'pantryStaples': 'रसोई की दैनिक सामग्री (QUICK ADD)',
      'dietaryPreferences': 'खान-पान की पसंद',
      'generateBtn': 'AI से असली रेसिपी बनाएं ✨',
      'generatingBtn': 'शेफ़ जेमिनी रेसिपी बना रहा है...',
      'clearAll': 'सब हटाएं',
      'addedIngredient': 'सामग्री जुड़ गई!',
      'pleaseSelectIngredient': 'कृपया कम से कम 1 सामग्री चुनें!',

      // Recipe Result Screen
      'prepTime': 'समय',
      'calories': 'कैलोरी',
      'servings': 'मात्रा',
      'ingredientsList': 'आवश्यक सामग्री और माप',
      'checkedOf': 'में से',
      'checked': 'तैयार',
      'toggleAll': 'सभी चुनें',
      'stepByStep': 'बनाने की विधि (Step-by-Step)',
      'steps': 'चरण',
      'save': 'सेव करें',
      'savedBtn': 'सेव किया गया',
      'startCooking': 'कुकिंग मोड शुरू करें 👨‍🍳',
      'cookingMode': 'लाइव कुकिंग मोड',
      'step': 'चरण',
      'stepTimer': 'टाइमर',
      'startTimer': 'टाइमर शुरू करें',
      'pause': 'रोकें',
      'reset': 'रीसेट',
      'previous': 'पिछला चरण',
      'nextStep': 'अगला चरण →',
      'finishCooking': 'खाना तैयार है! 🎉',
      'timerFinished': 'समय समाप्त! ⏰',
      'dishCompleted': 'वाह! आपका स्वादिष्ट व्यंजन तैयार है! 🍽️',
      'savedToCookbook': 'कुकबुक में सेव हो गया! 🧡',
      'removedFromSaved': 'सेव सूची से हटाया गया',

      // Saved Recipes Screen
      'mySavedRecipes': 'मेरी सेव की गई रेसिपी',
      'recipesSaved': 'रेसिपी सेव हैं',
      'filterSavedHint': 'सेव रेसिपी खोजें...',
      'noSavedYet': 'अभी कोई रेसिपी सेव नहीं है',
      'noSavedDesc':
          'होम स्क्रीन से अपनी पसंदीदा रेसिपी सेव करें या AI द्वारा नई रेसिपी बनाएं.',
      'exploreFeed': 'रेसिपी देखें',
      'pantryGen': 'नई रेसिपी बनाएं',

      // Language Modal
      'selectLanguage': 'भाषा चुनें / Select Language',
      'languageDesc': 'अपनी पसंदीदा भाषा चुनें.',
    },
    'en': {
      'welcomeBack': 'Welcome back',
      'goodEvening': 'Namaste, Chef! 👋',
      'searchHint': 'Search recipes, ingredients...',
      'recipeOfTheDay': 'Recipe of the Day',
      'editorsPick': "CHEF'S SIGNATURE",
      'foodCategories': 'Cuisine Categories',
      'all': 'All Dishes',
      'maharashtrian': 'Maharashtrian Special',
      'breakfast': 'Breakfast & Snacks',
      'traditional': 'Traditional Meals',
      'streetFood': 'Street Food',
      'fasting': 'Fasting & Satvik',
      'sweets': 'Desserts & Sweets',
      'trendingNow': 'Popular Maharashtrian & Indian Dishes',
      'recipesCount': 'recipes',
      'noRecipesFound': 'No matching recipes found.',

      // Bottom Nav
      'home': 'Home',
      'mealPlanner': 'What to Cook?',
      'generator': 'Recipe AI',
      'saved': 'Saved',

      // Meal Suggestion & Planner
      'mealSuggestionTitle': 'What Vegetable to Cook Today?',
      'mealSuggestionSubtitle':
          'Select available veggies and what you made yesterday; AI will suggest the perfect balanced meal without repeats!',
      'mealTime': 'Meal Timing',
      'breakfastOpt': '🥐 Breakfast',
      'lunchOpt': '🍛 Lunch',
      'dinnerOpt': '🍲 Dinner',
      'availableVeggies': 'Vegetables available at home',
      'familyMembers': 'Number of People',
      'cookingTime': 'Available Cooking Time',
      'cookedYesterday': 'What was cooked yesterday? (To avoid repeating)',
      'yesterdayHint': 'e.g. Potato Sabzi, Paneer, Matki, Dal Tadka...',
      'suggestMealBtn': 'Suggest Today’s Perfect Meal ✨',
      'suggestingMeal': 'Smart AI is deciding the menu...',
      'todaysRecommendation': 'Today’s Recommendation 🍽️',
      'whyThisDish': 'Why this dish? (AI Insights)',
      'completeThali': 'Complete Meal & Thali Pairing',
      'suggestAnother': 'Suggest Another Dish 🔄',
      'startCookingThis': 'Start Cooking This Dish 👨‍🍳',
      'weeklyPlannerTab': 'Weekly Planner',
      'dailySuggestionTab': 'Daily Meal Suggestion',
      'weeklyPlannerTitle': '7-Day Smart Meal Planner 📅',
      'weeklyPlannerSubtitle':
          'Effortless weekly balanced meal schedule designed for homemakers',

      // Pantry & Generator Screen
      'smartPantryTitle': 'Smart Kitchen AI Generator',
      'aiKitchenAssistant': 'POWERED BY GEMINI AI CHEF',
      'fridgeQuestion': "What ingredients do you have today?",
      'fridgeSubtitle':
          'Select your pantry items and Gemini AI will craft an authentic Indian & Maharashtrian recipe with exact measurements and steps.',
      'addCustom': 'ADD CUSTOM INGREDIENT',
      'customInputHint': 'e.g. Onions, potatoes, poha, besan, matki...',
      'selectedIngredients': 'SELECTED INGREDIENTS',
      'readyToCook': 'Ready for Gemini! ✨',
      'selectAtLeastOne': 'Select at least 1 ingredient',
      'noIngredientsAdded': 'No ingredients selected yet. Tap staples below!',
      'pantryStaples': 'ESSENTIAL INDIAN PANTRY STAPLES',
      'dietaryPreferences': 'PREFERENCES & DIET',
      'generateBtn': 'Generate Authentic Recipe with AI ✨',
      'generatingBtn': 'Chef Gemini is crafting your recipe...',
      'clearAll': 'Clear All',
      'addedIngredient': 'Added ingredient to pantry!',
      'pleaseSelectIngredient': 'Please select at least 1 ingredient!',

      // Recipe Result Screen
      'prepTime': 'PREP TIME',
      'calories': 'CALORIES',
      'servings': 'SERVINGS',
      'ingredientsList': 'Ingredients & Exact Measurements',
      'checkedOf': 'of',
      'checked': 'checked',
      'toggleAll': 'Toggle All',
      'stepByStep': 'Step-by-Step Cooking Method',
      'steps': 'Steps',
      'save': 'Save',
      'savedBtn': 'Saved',
      'startCooking': 'Start Cooking Mode 👨‍🍳',
      'cookingMode': 'Guided Cooking Mode',
      'step': 'STEP',
      'stepTimer': 'STEP TIMER',
      'startTimer': 'Start Timer',
      'pause': 'Pause',
      'reset': 'Reset',
      'previous': 'Previous Step',
      'nextStep': 'Next Step →',
      'finishCooking': 'Finish Cooking 🎉',
      'timerFinished': 'Step Timer Finished! ⏰',
      'dishCompleted': 'Swadisht! Your dish is ready to serve hot! 🍽️',
      'savedToCookbook': 'Saved to Cookbook! 🧡',
      'removedFromSaved': 'Removed from Saved',

      // Saved Recipes Screen
      'mySavedRecipes': 'My Saved Recipes',
      'recipesSaved': 'recipes saved',
      'filterSavedHint': 'Filter saved recipes...',
      'noSavedYet': 'No Saved Recipes Yet',
      'noSavedDesc':
          'Save traditional Indian & Maharashtrian dishes from the feed or generate custom recipes with AI.',
      'exploreFeed': 'Explore Feed',
      'pantryGen': 'Pantry Generator',

      // Language Modal
      'selectLanguage': 'Choose Language / भाषा निवडा',
      'languageDesc':
          'Select your preferred language for all screens and AI recipe generation.',
    },
    'es': {
      'welcomeBack': 'Bienvenido de nuevo',
      'goodEvening': '¡Hola, Chef! 👋',
      'searchHint': 'Buscar recetas, ingredientes...',
      'recipeOfTheDay': 'Receta del Día',
      'editorsPick': "ELECCIÓN DEL CHEF",
      'foodCategories': 'Categorías',
      'all': 'Todas las recetas',
      'maharashtrian': 'Especial Maharashtriano',
      'breakfast': 'Desayunos y Aperitivos',
      'traditional': 'Platos Tradicionales',
      'streetFood': 'Comida Callejera',
      'fasting': 'Especial Ayuno / Satvik',
      'sweets': 'Postres y Dulces',
      'trendingNow': 'Platos Populares de la India',
      'recipesCount': 'recetas',
      'noRecipesFound': 'No se encontraron recetas.',

      // Bottom Nav
      'home': 'Inicio',
      'mealPlanner': '¿Qué cocinar?',
      'generator': 'Receta AI',
      'saved': 'Guardadas',

      // Meal Suggestion & Planner
      'mealSuggestionTitle': '¿Qué verdura cocinar hoy?',
      'mealSuggestionSubtitle':
          'Selecciona las verduras disponibles y lo que cocinaste ayer; ¡la IA sugerirá un menú equilibrado!',
      'mealTime': 'Momento de comida',
      'breakfastOpt': '🥐 Desayuno',
      'lunchOpt': '🍛 Almuerzo',
      'dinnerOpt': '🍲 Cena',
      'availableVeggies': 'Verduras disponibles en casa',
      'familyMembers': 'Número de personas',
      'cookingTime': 'Tiempo de cocción',
      'cookedYesterday': '¿Qué cocinaste ayer? (Para no repetir)',
      'yesterdayHint': 'ej. Patata, Queso Paneer, Lentejas...',
      'suggestMealBtn': 'Sugerir Menú Perfecto ✨',
      'suggestingMeal': 'La IA está pensando...',
      'todaysRecommendation': 'Recomendación de Hoy 🍽️',
      'whyThisDish': '¿Por qué este plato? (Motivo IA)',
      'completeThali': 'Combinación Completa de Menú',
      'suggestAnother': 'Sugerir Otra Verdura 🔄',
      'startCookingThis': 'Empezar a Cocinar 👨‍🍳',
      'weeklyPlannerTab': 'Plan Semanal',
      'dailySuggestionTab': 'Sugerencia Diaria',
      'weeklyPlannerTitle': 'Planificador Inteligente de 7 Días 📅',
      'weeklyPlannerSubtitle':
          'Calendario equilibrado de comidas diseñado para el hogar',

      // Pantry & Generator Screen
      'smartPantryTitle': 'Generador Inteligente AI',
      'aiKitchenAssistant': 'CON LA TECNOLOGÍA DE GEMINI AI',
      'fridgeQuestion': "¿Qué ingredientes tienes hoy?",
      'fridgeSubtitle':
          'Selecciona tus ingredientes y Gemini AI inventará una auténtica receta india con pasos precisos.',
      'addCustom': 'AÑADIR INGREDIENTE',
      'customInputHint': 'ej. Cebolla, patata, poha, garbanzo...',
      'selectedIngredients': 'INGREDIENTES SELECCIONADOS',
      'readyToCook': '¡Listo para Gemini! ✨',
      'selectAtLeastOne': 'Selecciona al menos 1',
      'noIngredientsAdded': 'No hay ingredientes aún.',
      'pantryStaples': 'DESPENSA INDIA ESENCIAL',
      'dietaryPreferences': 'PREFERENCIAS DIETÉTICAS',
      'generateBtn': 'Generar Receta Auténtica ✨',
      'generatingBtn': 'El Chef Gemini está cocinando...',
      'clearAll': 'Borrar Todo',
      'addedIngredient': '¡Ingrediente añadido!',
      'pleaseSelectIngredient': '¡Selecciona al menos 1 ingrediente!',

      // Recipe Result Screen
      'prepTime': 'TIEMPO',
      'calories': 'CALORÍAS',
      'servings': 'PORCIONES',
      'ingredientsList': 'Lista de Ingredientes',
      'checkedOf': 'de',
      'checked': 'listo',
      'toggleAll': 'Marcar Todos',
      'stepByStep': 'Instrucciones Paso a Paso',
      'steps': 'Pasos',
      'save': 'Guardar',
      'savedBtn': 'Guardado',
      'startCooking': 'Modo Cocina 👨‍🍳',
      'cookingMode': 'Modo de Cocina',
      'step': 'PASO',
      'stepTimer': 'TEMPORIZADOR',
      'startTimer': 'Iniciar',
      'pause': 'Pausar',
      'reset': 'Reiniciar',
      'previous': 'Anterior',
      'nextStep': 'Siguiente →',
      'finishCooking': '¡Terminar! 🎉',
      'timerFinished': '¡Tiempo Terminado! ⏰',
      'dishCompleted': '¡Buen Provecho! 🍽️',
      'savedToCookbook': '¡Guardado! 🧡',
      'removedFromSaved': 'Eliminado',

      // Saved Recipes Screen
      'mySavedRecipes': 'Mis Recetas Guardadas',
      'recipesSaved': 'recetas guardadas',
      'filterSavedHint': 'Filtrar recetas...',
      'noSavedYet': 'No hay recetas guardadas',
      'noSavedDesc':
          'Guarda recetas indias tradicionales o crea nuevas con AI.',
      'exploreFeed': 'Explorar',
      'pantryGen': 'Generador',

      // Language Modal
      'selectLanguage': 'Elegir Idioma',
      'languageDesc': 'Selecciona tu idioma preferido.',
    },
  };

  static String get(String key, String languageCode) {
    final lang =
        _localizedValues.containsKey(languageCode) ? languageCode : 'mr';
    return _localizedValues[lang]?[key] ?? _localizedValues['en']?[key] ?? key;
  }
}
