class AppStrings {
  static const Map<String, String> languageNames = {
    'en': 'English',
    'mr': 'मराठी (Marathi)',
    'hi': 'हिंदी (Hindi)',
    'es': 'Español',
  };

  static const Map<String, String> languageCodes = {
    'en': 'English',
    'mr': 'मराठी',
    'hi': 'हिंदी',
    'es': 'Español',
  };

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'welcomeBack': 'Welcome back',
      'goodEvening': 'Good evening, Chef! 👋',
      'searchHint': 'Search recipes, ingredients...',
      'recipeOfTheDay': 'Recipe of the Day',
      'editorsPick': "EDITOR'S PICK",
      'foodCategories': 'Food Categories',
      'all': 'All Recipes',
      'quickMeals': 'Quick Meals',
      'highProtein': 'High Protein',
      'vegetarian': 'Vegetarian',
      'italian': 'Italian',
      'trendingNow': 'Trending Now',
      'recipesCount': 'recipes',
      'noRecipesFound': 'No matching recipes found.',
      
      // Bottom Nav
      'home': 'Home',
      'generator': 'Generator',
      'saved': 'Saved',

      // Pantry & Generator Screen
      'smartPantryTitle': 'Smart Pantry Generator',
      'aiKitchenAssistant': 'POWERED BY GEMINI AI',
      'fridgeQuestion': "What's in your fridge today?",
      'fridgeSubtitle': 'Select ingredients and Gemini AI will invent a chef-grade recipe with exact quantities & timers.',
      'addCustom': 'ADD CUSTOM INGREDIENT',
      'customInputHint': 'e.g. Chicken, heavy cream, garlic...',
      'selectedIngredients': 'SELECTED INGREDIENTS',
      'readyToCook': 'Ready for Gemini! ✨',
      'selectAtLeastOne': 'Select at least 1',
      'noIngredientsAdded': 'No ingredients selected yet. Tap staples below!',
      'pantryStaples': 'PANTRY STAPLES (QUICK ADD)',
      'dietaryPreferences': 'DIETARY PREFERENCES',
      'generateBtn': 'Generate Recipe with Gemini AI',
      'generatingBtn': 'Chef Gemini is cooking up ideas...',
      'clearAll': 'Clear All',
      'addedIngredient': 'Added ingredient to pantry!',
      'pleaseSelectIngredient': 'Please select at least 1 ingredient!',

      // Recipe Result Screen
      'prepTime': 'PREP TIME',
      'calories': 'CALORIES',
      'servings': 'SERVINGS',
      'ingredientsList': 'Ingredients List',
      'checkedOf': 'of',
      'checked': 'checked',
      'toggleAll': 'Toggle All',
      'stepByStep': 'Step-by-Step Instructions',
      'steps': 'Steps',
      'save': 'Save',
      'savedBtn': 'Saved',
      'startCooking': 'Start Cooking Mode',
      'cookingMode': 'Cooking Mode',
      'step': 'STEP',
      'stepTimer': 'STEP TIMER',
      'startTimer': 'Start Timer',
      'pause': 'Pause',
      'reset': 'Reset',
      'previous': 'Previous',
      'nextStep': 'Next Step →',
      'finishCooking': 'Finish Cooking 🎉',
      'timerFinished': 'Step Timer Finished! ⏰',
      'dishCompleted': 'Bon Appétit! Dish Completed! 🎉',
      'savedToCookbook': 'Saved to Cookbook! 🧡',
      'removedFromSaved': 'Removed from Saved',

      // Saved Recipes Screen
      'mySavedRecipes': 'My Saved Recipes',
      'recipesSaved': 'recipes saved',
      'filterSavedHint': 'Filter saved recipes...',
      'noSavedYet': 'No Saved Recipes Yet',
      'noSavedDesc': 'Save recipes from the home feed or generate custom dishes with your pantry ingredients.',
      'exploreFeed': 'Explore Feed',
      'pantryGen': 'Pantry Generator',
      
      // Language Modal
      'selectLanguage': 'Choose Language / भाषा निवडा',
      'languageDesc': 'Select your preferred language for all screens and AI recipe generation.',
    },
    'mr': {
      'welcomeBack': 'पुन्हा स्वागत आहे',
      'goodEvening': 'शुभ संध्याकाळ, शेफ! 👋',
      'searchHint': 'रेसिपी, साहित्य शोधा...',
      'recipeOfTheDay': 'आजची खास रेसिपी',
      'editorsPick': 'संपादकांची निवड',
      'foodCategories': 'खाद्य प्रकार',
      'all': 'सर्व रेसिपी',
      'quickMeals': 'झटपट जेवण',
      'highProtein': 'हाय प्रोटीन',
      'vegetarian': 'शाकाहारी',
      'italian': 'इटालियन',
      'trendingNow': 'सध्या लोकप्रिय',
      'recipesCount': 'रेसिपी',
      'noRecipesFound': 'कोणतीही रेसिपी सापडली नाही.',
      
      // Bottom Nav
      'home': 'होम',
      'generator': 'जनरेटर',
      'saved': 'सेव्ह केलेले',

      // Pantry & Generator Screen
      'smartPantryTitle': 'स्मार्ट पॅन्ट्री जनरेटर',
      'aiKitchenAssistant': 'GEMINI AI द्वारे संचालित',
      'fridgeQuestion': 'आज तुमच्या फ्रिजमध्ये काय आहे?',
      'fridgeSubtitle': 'साहित्य निवडा आणि Gemini AI तुमच्यासाठी अचूक प्रमाण आणि वेळेसह खास रेसिपी तयार करेल.',
      'addCustom': 'इतर साहित्य जोडा',
      'customInputHint': 'उदा. चिकन, मलई, लसूण, कांदा...',
      'selectedIngredients': 'निवडलेले साहित्य',
      'readyToCook': 'तयार आहे! ✨',
      'selectAtLeastOne': 'किमान १ साहित्य निवडा',
      'noIngredientsAdded': 'अद्याप कोणतेही साहित्य निवडलेले नाही. खालील साहित्यावर टॅप करा!',
      'pantryStaples': 'घरातील मुख्य साहित्य (झटपट जोडा)',
      'dietaryPreferences': 'आहार प्राधान्ये',
      'generateBtn': 'Gemini AI सह रेसिपी तयार करा',
      'generatingBtn': 'शेफ Gemini रेसिपी बनवत आहे...',
      'clearAll': 'सर्व हटवा',
      'addedIngredient': 'साहित्य जोडले गेले!',
      'pleaseSelectIngredient': 'कृपया किमान १ साहित्य निवडा!',

      // Recipe Result Screen
      'prepTime': 'तयारी वेळ',
      'calories': 'कॅलरी',
      'servings': 'सर्व्हिंग्ज',
      'ingredientsList': 'साहित्याची यादी',
      'checkedOf': 'पैकी',
      'checked': 'तयार',
      'toggleAll': 'सर्व निवडा',
      'stepByStep': 'टप्प्याटप्प्याने पाककृती सूचना',
      'steps': 'टप्पे',
      'save': 'सेव्ह करा',
      'savedBtn': 'सेव्ह केले',
      'startCooking': 'कुकिंग मोड सुरू करा',
      'cookingMode': 'कुकिंग मोड (पाककृती मार्गदर्शक)',
      'step': 'टप्पा',
      'stepTimer': 'स्टेप टायमर',
      'startTimer': 'टायमर सुरू करा',
      'pause': 'थांबवा',
      'reset': 'पुन्हा सुरू करा',
      'previous': 'मागील',
      'nextStep': 'पुढील टप्पा →',
      'finishCooking': 'पाककृती पूर्ण झाली 🎉',
      'timerFinished': 'स्टेप टायमर पूर्ण झाला! ⏰',
      'dishCompleted': 'वाह! डिश तयार झाली आहे, आनंद घ्या! 🎉',
      'savedToCookbook': 'कुकबुकमध्ये सेव्ह केले! 🧡',
      'removedFromSaved': 'सेव्हमधून काढले',

      // Saved Recipes Screen
      'mySavedRecipes': 'माझ्या सेव्ह केलेल्या रेसिपी',
      'recipesSaved': 'रेसिपी सेव्ह केल्या',
      'filterSavedHint': 'सेव्ह केलेल्या रेसिपी शोधा...',
      'noSavedYet': 'अद्याप कोणतीही रेसिपी सेव्ह केलेली नाही',
      'noSavedDesc': 'होम फीडवरून रेसिपी सेव्ह करा किंवा आपल्या साहित्यासह नवीन रेसिपी तयार करा.',
      'exploreFeed': 'रेसिपी एक्सप्लोर करा',
      'pantryGen': 'पॅन्ट्री जनरेटर',

      // Language Modal
      'selectLanguage': 'भाषा निवडा / Choose Language',
      'languageDesc': 'सर्व स्क्रीन आणि AI रेसिपी निर्मितीसाठी आपली आवडती भाषा निवडा.',
    },
    'hi': {
      'welcomeBack': 'वापसी पर स्वागत है',
      'goodEvening': 'शुभ संध्या, शेफ! 👋',
      'searchHint': 'व्यंजन, सामग्री खोजें...',
      'recipeOfTheDay': 'आज की खास रेसिपी',
      'editorsPick': 'संपादक की पसंद',
      'foodCategories': 'व्यंजन श्रेणियां',
      'all': 'सभी रेसिपी',
      'quickMeals': 'झटपट भोजन',
      'highProtein': 'हाई प्रोटीन',
      'vegetarian': 'शाकाहारी',
      'italian': 'इटैलियन',
      'trendingNow': 'ट्रेंडिंग रेसिपी',
      'recipesCount': 'रेसिपी',
      'noRecipesFound': 'कोई रेसिपी नहीं मिली।',
      
      // Bottom Nav
      'home': 'होम',
      'generator': 'जेनरेटर',
      'saved': 'सेव्ड',

      // Pantry & Generator Screen
      'smartPantryTitle': 'स्मार्ट पैंट्री जेनरेटर',
      'aiKitchenAssistant': 'GEMINI AI द्वारा संचालित',
      'fridgeQuestion': 'आज आपके फ्रिज में क्या है?',
      'fridgeSubtitle': 'सामग्री चुनें और Gemini AI सटीक मात्रा और टाइमर के साथ आपके लिए रेसिपी तैयार करेगा।',
      'addCustom': 'अन्य सामग्री जोड़ें',
      'customInputHint': 'उदा. चिकन, मलाई, लहसुन, प्याज...',
      'selectedIngredients': 'चुनी गई सामग्री',
      'readyToCook': 'तैयार है! ✨',
      'selectAtLeastOne': 'कम से कम 1 सामग्री चुनें',
      'noIngredientsAdded': 'अभी कोई सामग्री नहीं चुनी गई है। नीचे टैप करें!',
      'pantryStaples': 'रसोई सामग्री (त्वरित जोड़ें)',
      'dietaryPreferences': 'आहार प्राथमिकताएं',
      'generateBtn': 'Gemini AI से रेसिपी बनाएं',
      'generatingBtn': 'शेफ Gemini रेसिपी बना रहा है...',
      'clearAll': 'सभी हटाएं',
      'addedIngredient': 'सामग्री जोड़ी गई!',
      'pleaseSelectIngredient': 'कृपया कम से कम 1 सामग्री चुनें!',

      // Recipe Result Screen
      'prepTime': 'तैयारी का समय',
      'calories': 'कैलोरी',
      'servings': 'सर्विंग्स',
      'ingredientsList': 'सामग्री की सूची',
      'checkedOf': 'में से',
      'checked': 'तैयार',
      'toggleAll': 'सभी चुनें',
      'stepByStep': 'चरण-दर-चरण पकाने के निर्देश',
      'steps': 'कदम',
      'save': 'सेव करें',
      'savedBtn': 'सेव्ड',
      'startCooking': 'कुकिंग मोड शुरू करें',
      'cookingMode': 'कुकिंग मोड',
      'step': 'चरण',
      'stepTimer': 'स्टेप टाइमर',
      'startTimer': 'टाइमर शुरू करें',
      'pause': 'रोकें',
      'reset': 'रीसेट',
      'previous': 'पिछला',
      'nextStep': 'अगला कदम →',
      'finishCooking': 'कुकिंग पूरी हुई 🎉',
      'timerFinished': 'स्टेप टाइमर समाप्त! ⏰',
      'dishCompleted': 'स्वादिष्ट भोजन तैयार है! 🎉',
      'savedToCookbook': 'कुकबुक में सेव किया गया! 🧡',
      'removedFromSaved': 'सेव्ड से हटाया गया',

      // Saved Recipes Screen
      'mySavedRecipes': 'मेरी सेव की गई रेसिपी',
      'recipesSaved': 'रेसिपी सेव की गईं',
      'filterSavedHint': 'सेव की गई रेसिपी खोजें...',
      'noSavedYet': 'अभी कोई रेसिपी सेव नहीं है',
      'noSavedDesc': 'होम फीड से रेसिपी सेव करें या अपनी सामग्री से नई रेसिपी बनाएं।',
      'exploreFeed': 'रेसिपी खोजें',
      'pantryGen': 'पैंट्री जेनरेटर',

      // Language Modal
      'selectLanguage': 'भाषा चुनें / Select Language',
      'languageDesc': 'सभी स्क्रीन और AI रेसिपी निर्माण के लिए अपनी पसंदीदा भाषा चुनें।',
    },
    'es': {
      'welcomeBack': 'Bienvenido de nuevo',
      'goodEvening': '¡Buenas tardes, Chef! 👋',
      'searchHint': 'Buscar recetas, ingredientes...',
      'recipeOfTheDay': 'Receta del Día',
      'editorsPick': 'ELECCIÓN DEL CHEF',
      'foodCategories': 'Categorías',
      'all': 'Todas las recetas',
      'quickMeals': 'Comidas Rápidas',
      'highProtein': 'Alta Proteína',
      'vegetarian': 'Vegetariano',
      'italian': 'Italiano',
      'trendingNow': 'Tendencias',
      'recipesCount': 'recetas',
      'noRecipesFound': 'No se encontraron recetas.',
      
      // Bottom Nav
      'home': 'Inicio',
      'generator': 'Generador',
      'saved': 'Guardados',

      // Pantry & Generator Screen
      'smartPantryTitle': 'Generador de Despensa Inteligente',
      'aiKitchenAssistant': 'IMPULSADO POR GEMINI AI',
      'fridgeQuestion': '¿Qué tienes en tu refrigerador hoy?',
      'fridgeSubtitle': 'Selecciona ingredientes y Gemini AI inventará una receta gourmet con cantidades exactas y temporizadores.',
      'addCustom': 'AÑADIR INGREDIENTE',
      'customInputHint': 'ej. Pollo, crema, ajo...',
      'selectedIngredients': 'INGREDIENTES SELECCIONADOS',
      'readyToCook': '¡Listo para cocinar! ✨',
      'selectAtLeastOne': 'Selecciona al menos 1',
      'noIngredientsAdded': 'No hay ingredientes aún. ¡Toca los ingredientes abajo!',
      'pantryStaples': 'DESPENSA BÁSICA',
      'dietaryPreferences': 'PREFERENCIAS DIETÉTICAS',
      'generateBtn': 'Generar Receta con Gemini AI',
      'generatingBtn': 'Chef Gemini está cocinando ideas...',
      'clearAll': 'Limpiar Todo',
      'addedIngredient': '¡Ingrediente añadido!',
      'pleaseSelectIngredient': '¡Por favor selecciona al menos 1 ingrediente!',

      // Recipe Result Screen
      'prepTime': 'TIEMPO',
      'calories': 'CALORÍAS',
      'servings': 'PORCIONES',
      'ingredientsList': 'Lista de Ingredientes',
      'checkedOf': 'de',
      'checked': 'listos',
      'toggleAll': 'Seleccionar Todo',
      'stepByStep': 'Instrucciones Paso a Paso',
      'steps': 'Pasos',
      'save': 'Guardar',
      'savedBtn': 'Guardado',
      'startCooking': 'Iniciar Modo Cocina',
      'cookingMode': 'Modo Cocina',
      'step': 'PASO',
      'stepTimer': 'TEMPORIZADOR',
      'startTimer': 'Iniciar',
      'pause': 'Pausar',
      'reset': 'Reiniciar',
      'previous': 'Anterior',
      'nextStep': 'Siguiente Paso →',
      'finishCooking': '¡Terminar Cocina! 🎉',
      'timerFinished': '¡Temporizador terminado! ⏰',
      'dishCompleted': '¡Buen provecho! Plato terminado 🎉',
      'savedToCookbook': '¡Guardado en el recetario! 🧡',
      'removedFromSaved': 'Eliminado de guardados',

      // Saved Recipes Screen
      'mySavedRecipes': 'Mis Recetas Guardadas',
      'recipesSaved': 'recetas guardadas',
      'filterSavedHint': 'Filtrar recetas guardadas...',
      'noSavedYet': 'Sin recetas guardadas aún',
      'noSavedDesc': 'Guarda recetas desde el inicio o genera platos con tus ingredientes.',
      'exploreFeed': 'Explorar',
      'pantryGen': 'Generador',

      // Language Modal
      'selectLanguage': 'Seleccionar Idioma',
      'languageDesc': 'Elige tu idioma preferido para todas las pantallas y la generación de recetas AI.',
    }
  };

  static String get(String key, String langCode) {
    final langMap = _localizedValues[langCode] ?? _localizedValues['en']!;
    return langMap[key] ?? _localizedValues['en']![key] ?? key;
  }
}
