class AppStrings {
  static const Map<String, String> languageNames = {
    'mr': 'मराठी (Marathi)',
    'hi': 'हिंदी (Hindi)',
    'en': 'English',
    'es': 'Español',
  };

  static const Map<String, String> languageCodes = {
    'mr': 'मराठी',
    'hi': 'हिंदी',
    'en': 'English',
    'es': 'Español',
  };

  static const Map<String, Map<String, String>> _localizedValues = {
    'mr': {
      'welcomeBack': 'पुन्हा स्वागत आहे',
      'goodEvening': 'नमस्कार, शेफ! 👋',
      'searchHint': 'रेसिपी, भाजी, साहित्य शोधा...',
      'recipeOfTheDay': 'आजची खास रेसिपी',
      'editorsPick': "शेफची पहिली पसंती",
      'foodCategories': 'रेसिपी प्रकार',
      'all': 'सर्व रेसिपी',
      'maharashtrian': 'महाराष्ट्रीयन खास',
      'breakfast': 'खमंग नाश्ता',
      'traditional': 'पारंपरिक जेवण',
      'streetFood': 'स्ट्रीट फूड',
      'fasting': 'उपवास स्पेशल',
      'sweets': 'गोडधोड',
      'trendingNow': 'लोकप्रिय महाराष्ट्रीयन डिशेस',
      'recipesCount': 'रेसिपी',
      'noRecipesFound': 'कोणतीही रेसिपी सापडली नाही.',

      // Bottom Nav
      'home': 'होम',
      'generator': 'रेसिपी AI',
      'saved': 'माझ्या रेसिपी',

      // Pantry & Generator Screen
      'smartPantryTitle': 'किचन रेसिपी AI जनरेटर',
      'aiKitchenAssistant': 'GEMINI AI कुकिंग शेफ',
      'fridgeQuestion': "आज स्वयंपाकघरात काय साहित्य आहे?",
      'fridgeSubtitle':
          'साहित्य निवडा किंवा नाव टाका; जेमिनी AI अस्सल चवीची, अचूक प्रमाणासह नवीन रेसिपी तयार करेल!',
      'addCustom': 'इतर साहित्य जोडा',
      'customInputHint': 'उदा. कांदा, लसूण, पोहे, बेसन, मटकी...',
      'selectedIngredients': 'निवडलेले साहित्य',
      'readyToCook': 'रेसिपीसाठी सज्ज! ✨',
      'selectAtLeastOne': 'किमान १ साहित्य निवडा',
      'noIngredientsAdded':
          'अद्याप कोणतेही साहित्य निवडलेले नाही. खालील साहित्यावर टॅप करा!',
      'pantryStaples': 'किचनमधील रोजचे साहित्य (QUICK ADD)',
      'dietaryPreferences': 'खाण्याच्या आवडी / डाएट',
      'generateBtn': 'AI सह अस्सल रेसिपी बनवा ✨',
      'generatingBtn': 'शेफ जेमिनी रेसिपी तयार करत आहे...',
      'clearAll': 'सर्व हटवा',
      'addedIngredient': 'साहित्य जोडले गेले!',
      'pleaseSelectIngredient': 'कृपया किमान १ तरी साहित्य निवडा!',

      // Recipe Result Screen
      'prepTime': 'वेळ',
      'calories': 'कॅलरी',
      'servings': 'प्रमाण',
      'ingredientsList': 'आवश्यक साहित्य व प्रमाण',
      'checkedOf': 'पैकी',
      'checked': 'तयार',
      'toggleAll': 'सर्व निवडा',
      'stepByStep': 'कृती (Step-by-Step कृतीचे टप्पे)',
      'steps': 'टप्पे',
      'save': 'सेव्ह करा',
      'savedBtn': 'सेव्ह केले',
      'startCooking': 'कुकिंग मोड सुरू करा 👨‍🍳',
      'cookingMode': 'लाईव्ह कुकिंग मोड',
      'step': 'टप्पा',
      'stepTimer': 'टायमर',
      'startTimer': 'टायमर सुरू करा',
      'pause': 'थांबवा',
      'reset': 'रिसेट',
      'previous': 'मागील टप्पा',
      'nextStep': 'पुढील टप्पा →',
      'finishCooking': 'स्वयंपाक पूर्ण झाला! 🎉',
      'timerFinished': 'वेळ पूर्ण झाली! ⏰',
      'dishCompleted': 'वाह! तुमची डिश तयार झाली आहे! गरमागरम आस्वाद घ्या! 🍽️',
      'savedToCookbook': 'रेसिपी सेव्ह झाली! 🧡',
      'removedFromSaved': 'सेव्ह लिस्टमधून काढले',

      // Saved Recipes Screen
      'mySavedRecipes': 'माझ्या सेव्ह केलेल्या रेसिपी',
      'recipesSaved': 'रेसिपी सेव्ह केल्या',
      'filterSavedHint': 'सेव्ह केलेल्या रेसिपी शोधा...',
      'noSavedYet': 'अद्याप एकही रेसिपी सेव्ह केलेली नाही',
      'noSavedDesc':
          'होम स्क्रीनवरून तुमच्या आवडत्या महाराष्ट्रीयन रेसिपी सेव्ह करा किंवा AI ने नवीन तयार करा.',
      'exploreFeed': 'रेसिपी पहा',
      'pantryGen': 'नवीन रेसिपी बनवा',

      // Language Modal
      'selectLanguage': 'भाषा निवडा / Choose Language',
      'languageDesc': 'आपल्या आवडीनुसार संपूर्ण ॲप आणि रेसिपीसाठी भाषा निवडा.',
    },
    'hi': {
      'welcomeBack': 'वापसी पर स्वागत है',
      'goodEvening': 'नमस्ते, शेफ़! 👋',
      'searchHint': 'रेसिपी, सामग्री खोजें...',
      'recipeOfTheDay': 'आज की खास रेसिपी',
      'editorsPick': "शेफ़ की पसंद",
      'foodCategories': 'व्यंजन श्रेणियां',
      'all': 'सभी रेसिपी',
      'maharashtrian': 'महाराष्ट्रीयन खास',
      'breakfast': 'स्वादिष्ट नाश्ता',
      'traditional': 'पारंपरिक भोजन',
      'streetFood': 'स्ट्रीट फूड',
      'fasting': 'व्रत/उपवास स्पेशल',
      'sweets': 'मिठाई',
      'trendingNow': 'लोकप्रिय भारतीय व्यंजन',
      'recipesCount': 'रेसिपी',
      'noRecipesFound': 'कोई रेसिपी नहीं मिली.',

      // Bottom Nav
      'home': 'होम',
      'generator': 'रेसिपी AI',
      'saved': 'सेव की गई',

      // Pantry & Generator Screen
      'smartPantryTitle': 'रसोई रेसिपी AI जनरेटर',
      'aiKitchenAssistant': 'GEMINI AI कुकिंग शेफ़',
      'fridgeQuestion': "आज आपकी रसोई में क्या सामग्री है?",
      'fridgeSubtitle':
          'सामग्री चुनें और जेमिनी AI सटीक मात्रा और समय के साथ असली स्वादिष्ट रेसिपी तैयार करेगा.',
      'addCustom': 'अन्य सामग्री जोड़ें',
      'customInputHint': 'उदा. प्याज, आलू, पोहा, बेसन, मटर...',
      'selectedIngredients': 'चुनी गई सामग्री',
      'readyToCook': 'रेसिपी के लिए तैयार! ✨',
      'selectAtLeastOne': 'कम से कम 1 सामग्री चुनें',
      'noIngredientsAdded':
          'अभी कोई सामग्री नहीं चुनी गई. नीचे दिए गए विकल्पों पर टैप करें!',
      'pantryStaples': 'रसोई की दैनिक सामग्री (QUICK ADD)',
      'dietaryPreferences': 'खान-पान की पसंद',
      'generateBtn': 'AI से असली रेसिपी बनाएं ✨',
      'generatingBtn': 'शेफ़ जेमिनी रेसिपी बना रहा है...',
      'clearAll': 'सब हटाएं',
      'addedIngredient': 'सामग्री जुड़ गई!',
      'pleaseSelectIngredient': 'कृपया कम से कम 1 सामग्री चुनें!',

      // Recipe Result Screen
      'prepTime': 'समय',
      'calories': 'कैलोरी',
      'servings': 'मात्रा',
      'ingredientsList': 'आवश्यक सामग्री और माप',
      'checkedOf': 'में से',
      'checked': 'तैयार',
      'toggleAll': 'सभी चुनें',
      'stepByStep': 'बनाने की विधि (Step-by-Step)',
      'steps': 'चरण',
      'save': 'सेव करें',
      'savedBtn': 'सेव किया गया',
      'startCooking': 'कुकिंग मोड शुरू करें 👨‍🍳',
      'cookingMode': 'लाइव कुकिंग मोड',
      'step': 'चरण',
      'stepTimer': 'टाइमर',
      'startTimer': 'टाइमर शुरू करें',
      'pause': 'रोकें',
      'reset': 'रीसेट',
      'previous': 'पिछला चरण',
      'nextStep': 'अगला चरण →',
      'finishCooking': 'खाना तैयार है! 🎉',
      'timerFinished': 'समय समाप्त! ⏰',
      'dishCompleted': 'वाह! आपका स्वादिष्ट व्यंजन तैयार है! 🍽️',
      'savedToCookbook': 'कुकबुक में सेव हो गया! 🧡',
      'removedFromSaved': 'सेव सूची से हटाया गया',

      // Saved Recipes Screen
      'mySavedRecipes': 'मेरी सेव की गई रेसिपी',
      'recipesSaved': 'रेसिपी सेव हैं',
      'filterSavedHint': 'सेव रेसिपी खोजें...',
      'noSavedYet': 'अभी कोई रेसिपी सेव नहीं है',
      'noSavedDesc':
          'होम स्क्रीन से अपनी पसंदीदा रेसिपी सेव करें या AI द्वारा नई रेसिपी बनाएं.',
      'exploreFeed': 'रेसिपी देखें',
      'pantryGen': 'नई रेसिपी बनाएं',

      // Language Modal
      'selectLanguage': 'भाषा चुनें / Select Language',
      'languageDesc': 'अपनी पसंदीदा भाषा चुनें.',
    },
    'en': {
      'welcomeBack': 'Welcome back',
      'goodEvening': 'Namaste, Chef! 👋',
      'searchHint': 'Search recipes, ingredients...',
      'recipeOfTheDay': 'Recipe of the Day',
      'editorsPick': "CHEF'S SIGNATURE",
      'foodCategories': 'Cuisine Categories',
      'all': 'All Dishes',
      'maharashtrian': 'Maharashtrian Special',
      'breakfast': 'Breakfast & Snacks',
      'traditional': 'Traditional Meals',
      'streetFood': 'Street Food',
      'fasting': 'Fasting & Satvik',
      'sweets': 'Desserts & Sweets',
      'trendingNow': 'Popular Maharashtrian & Indian Dishes',
      'recipesCount': 'recipes',
      'noRecipesFound': 'No matching recipes found.',

      // Bottom Nav
      'home': 'Home',
      'generator': 'Recipe AI',
      'saved': 'Saved',

      // Pantry & Generator Screen
      'smartPantryTitle': 'Smart Kitchen AI Generator',
      'aiKitchenAssistant': 'POWERED BY GEMINI AI CHEF',
      'fridgeQuestion': "What ingredients do you have today?",
      'fridgeSubtitle':
          'Select your pantry items and Gemini AI will craft an authentic Indian & Maharashtrian recipe with exact measurements and steps.',
      'addCustom': 'ADD CUSTOM INGREDIENT',
      'customInputHint': 'e.g. Onions, potatoes, poha, besan, matki...',
      'selectedIngredients': 'SELECTED INGREDIENTS',
      'readyToCook': 'Ready for Gemini! ✨',
      'selectAtLeastOne': 'Select at least 1 ingredient',
      'noIngredientsAdded': 'No ingredients selected yet. Tap staples below!',
      'pantryStaples': 'ESSENTIAL INDIAN PANTRY STAPLES',
      'dietaryPreferences': 'PREFERENCES & DIET',
      'generateBtn': 'Generate Authentic Recipe with AI ✨',
      'generatingBtn': 'Chef Gemini is crafting your recipe...',
      'clearAll': 'Clear All',
      'addedIngredient': 'Added ingredient to pantry!',
      'pleaseSelectIngredient': 'Please select at least 1 ingredient!',

      // Recipe Result Screen
      'prepTime': 'PREP TIME',
      'calories': 'CALORIES',
      'servings': 'SERVINGS',
      'ingredientsList': 'Ingredients & Exact Measurements',
      'checkedOf': 'of',
      'checked': 'checked',
      'toggleAll': 'Toggle All',
      'stepByStep': 'Step-by-Step Cooking Method',
      'steps': 'Steps',
      'save': 'Save',
      'savedBtn': 'Saved',
      'startCooking': 'Start Cooking Mode 👨‍🍳',
      'cookingMode': 'Guided Cooking Mode',
      'step': 'STEP',
      'stepTimer': 'STEP TIMER',
      'startTimer': 'Start Timer',
      'pause': 'Pause',
      'reset': 'Reset',
      'previous': 'Previous Step',
      'nextStep': 'Next Step →',
      'finishCooking': 'Finish Cooking 🎉',
      'timerFinished': 'Step Timer Finished! ⏰',
      'dishCompleted': 'Swadisht! Your dish is ready to serve hot! 🍽️',
      'savedToCookbook': 'Saved to Cookbook! 🧡',
      'removedFromSaved': 'Removed from Saved',

      // Saved Recipes Screen
      'mySavedRecipes': 'My Saved Recipes',
      'recipesSaved': 'recipes saved',
      'filterSavedHint': 'Filter saved recipes...',
      'noSavedYet': 'No Saved Recipes Yet',
      'noSavedDesc':
          'Save traditional Indian & Maharashtrian dishes from the feed or generate custom recipes with AI.',
      'exploreFeed': 'Explore Feed',
      'pantryGen': 'Pantry Generator',

      // Language Modal
      'selectLanguage': 'Choose Language / भाषा निवडा',
      'languageDesc':
          'Select your preferred language for all screens and AI recipe generation.',
    },
    'es': {
      'welcomeBack': 'Bienvenido de nuevo',
      'goodEvening': '¡Hola, Chef! 👋',
      'searchHint': 'Buscar recetas, ingredientes...',
      'recipeOfTheDay': 'Receta del Día',
      'editorsPick': "ELECCIÓN DEL CHEF",
      'foodCategories': 'Categorías',
      'all': 'Todas las recetas',
      'maharashtrian': 'Especial Maharashtriano',
      'breakfast': 'Desayunos y Aperitivos',
      'traditional': 'Platos Tradicionales',
      'streetFood': 'Comida Callejera',
      'fasting': 'Especial Ayuno / Satvik',
      'sweets': 'Postres y Dulces',
      'trendingNow': 'Platos Populares de la India',
      'recipesCount': 'recetas',
      'noRecipesFound': 'No se encontraron recetas.',

      // Bottom Nav
      'home': 'Inicio',
      'generator': 'Receta AI',
      'saved': 'Guardadas',

      // Pantry & Generator Screen
      'smartPantryTitle': 'Generador Inteligente AI',
      'aiKitchenAssistant': 'CON LA TECNOLOGÍA DE GEMINI AI',
      'fridgeQuestion': "¿Qué ingredientes tienes hoy?",
      'fridgeSubtitle':
          'Selecciona tus ingredientes y Gemini AI inventará una auténtica receta india con pasos precisos.',
      'addCustom': 'AÑADIR INGREDIENTE',
      'customInputHint': 'ej. Cebolla, patata, poha, garbanzo...',
      'selectedIngredients': 'INGREDIENTES SELECCIONADOS',
      'readyToCook': '¡Listo para Gemini! ✨',
      'selectAtLeastOne': 'Selecciona al menos 1',
      'noIngredientsAdded': 'No hay ingredientes aún.',
      'pantryStaples': 'DESPENSA INDIA ESENCIAL',
      'dietaryPreferences': 'PREFERENCIAS DIETÉTICAS',
      'generateBtn': 'Generar Receta Auténtica ✨',
      'generatingBtn': 'El Chef Gemini está cocinando...',
      'clearAll': 'Borrar Todo',
      'addedIngredient': '¡Ingrediente añadido!',
      'pleaseSelectIngredient': '¡Selecciona al menos 1 ingrediente!',

      // Recipe Result Screen
      'prepTime': 'TIEMPO',
      'calories': 'CALORÍAS',
      'servings': 'PORCIONES',
      'ingredientsList': 'Lista de Ingredientes',
      'checkedOf': 'de',
      'checked': 'listo',
      'toggleAll': 'Marcar Todos',
      'stepByStep': 'Instrucciones Paso a Paso',
      'steps': 'Pasos',
      'save': 'Guardar',
      'savedBtn': 'Guardado',
      'startCooking': 'Modo Cocina 👨‍🍳',
      'cookingMode': 'Modo de Cocina',
      'step': 'PASO',
      'stepTimer': 'TEMPORIZADOR',
      'startTimer': 'Iniciar',
      'pause': 'Pausar',
      'reset': 'Reiniciar',
      'previous': 'Anterior',
      'nextStep': 'Siguiente →',
      'finishCooking': '¡Terminar! 🎉',
      'timerFinished': '¡Tiempo Terminado! ⏰',
      'dishCompleted': '¡Buen Provecho! 🍽️',
      'savedToCookbook': '¡Guardado! 🧡',
      'removedFromSaved': 'Eliminado',

      // Saved Recipes Screen
      'mySavedRecipes': 'Mis Recetas Guardadas',
      'recipesSaved': 'recetas guardadas',
      'filterSavedHint': 'Filtrar recetas...',
      'noSavedYet': 'No hay recetas guardadas',
      'noSavedDesc':
          'Guarda recetas indias tradicionales o crea nuevas con AI.',
      'exploreFeed': 'Explorar',
      'pantryGen': 'Generador',

      // Language Modal
      'selectLanguage': 'Elegir Idioma',
      'languageDesc': 'Selecciona tu idioma preferido.',
    },
  };

  static String get(String key, String languageCode) {
    final lang =
        _localizedValues.containsKey(languageCode) ? languageCode : 'mr';
    return _localizedValues[lang]?[key] ?? _localizedValues['en']?[key] ?? key;
  }
}
